apiVersion: apps/v1
kind: Deployment
metadata:
  name: notesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notesapp
  template:
    metadata:
      labels:
        app: notesapp
    spec:
      containers:
      - name: notesapp
        image: timkerekes/acg-flask-web-app
        ports:
        - containerPort: 80
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: notesapp
spec:
  type: NodePort
  selector:
    app: notesapp
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: notesapp

spec:
  rules:
  - host: 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: notesapp
            port:
              number: 80