name: Docker Build Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    if: ${{ !startsWith(github.event.head_commit.modified, '.github/workflows') }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_PASSWORD }}
        logout: true
        
    - name: Docker Build & Push
      run: |
        docker build -t ${{ secrets.HUB_USERNAME }}/acg-flask-web-app:${{ github.sha }} .
        docker push ${{ secrets.HUB_URL }}/acg-flask-web-app:${{ github.sha }}
